-- ============================================
-- Student Placement Tracker - Database Schema
-- ============================================

CREATE DATABASE IF NOT EXISTS placement_tracker
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE placement_tracker;

-- ---------- Admins (Authentication) ----------
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------- Students ----------
CREATE TABLE IF NOT EXISTS students (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    roll_number VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    branch VARCHAR(50) NOT NULL,
    cgpa DECIMAL(4,2) NOT NULL CHECK (cgpa >= 0 AND cgpa <= 10),
    skills VARCHAR(500),
    phone_number VARCHAR(15),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------- Companies ----------
CREATE TABLE IF NOT EXISTS companies (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL,
    ctc DECIMAL(10,2) NOT NULL,
    location VARCHAR(100) NOT NULL,
    eligibility_cgpa DECIMAL(4,2) NOT NULL CHECK (eligibility_cgpa >= 0 AND eligibility_cgpa <= 10),
    last_date_to_apply DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------- Applications (join table with extra attributes) ----------
CREATE TABLE IF NOT EXISTS applications (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    status ENUM('APPLIED', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'SELECTED', 'REJECTED')
        NOT NULL DEFAULT 'APPLIED',
    applied_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_application_student
        FOREIGN KEY (student_id) REFERENCES students(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_application_company
        FOREIGN KEY (company_id) REFERENCES companies(id)
        ON DELETE CASCADE,

    CONSTRAINT unique_student_company
        UNIQUE (student_id, company_id)
) ENGINE=InnoDB;

-- ============================================
-- Seed data (optional, for local testing)
-- ============================================

-- NOTE: We do NOT insert the default admin here. BCrypt hashes include a random
-- salt and must be generated by BCrypt itself - typing one by hand in SQL risks
-- getting it wrong, and a wrong hash means login silently fails. Instead, the
-- Spring Boot app creates the default admin automatically on first startup
-- (see config/DataSeeder.java):
--   username: admin   password: Admin@123

INSERT INTO students (name, roll_number, email, branch, cgpa, skills, phone_number) VALUES
('Aarav Sharma', 'JEC21CS001', 'aarav.sharma@jecrc.edu', 'CSE', 8.75, 'Java, Spring Boot, React', '9876543210'),
('Priya Verma', 'JEC21CS002', 'priya.verma@jecrc.edu', 'CSE', 9.10, 'Python, ML, SQL', '9876543211'),
('Rohan Gupta', 'JEC21IT001', 'rohan.gupta@jecrc.edu', 'IT', 7.60, 'JavaScript, Node.js', '9876543212'),
('Sneha Reddy', 'JEC21EC001', 'sneha.reddy@jecrc.edu', 'ECE', 8.20, 'C++, Embedded Systems', '9876543213')
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO companies (company_name, ctc, location, eligibility_cgpa, last_date_to_apply) VALUES
('TechNova Solutions', 12.50, 'Bengaluru', 7.50, '2026-08-15'),
('CloudBridge Systems', 9.00, 'Pune', 7.00, '2026-08-20'),
('DataForge Analytics', 15.00, 'Hyderabad', 8.00, '2026-08-25')
ON DUPLICATE KEY UPDATE company_name = company_name;

INSERT INTO applications (student_id, company_id, status) VALUES
(1, 1, 'SELECTED'),
(1, 2, 'REJECTED'),
(2, 1, 'INTERVIEW_SCHEDULED'),
(2, 3, 'APPLIED'),
(3, 2, 'SHORTLISTED'),
(4, 1, 'APPLIED')
ON DUPLICATE KEY UPDATE status = status;
